server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/realworldapp-local"
    username: root
    password: passWord
  jooq:
    sql-dialect: Postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://${AUTH0_DOMAIN}/"
  flyway:
    locations: "classpath:db/migration"
logging:
  level:
    root: DEBUG
auth0:
  audience: "https://${AUTH0_DOMAIN}/api/v2/"
  domain: "${AUTH0_DOMAIN}"
  clientId: "${AUTH0_CLIENT_ID}"
  clientSecret: "${AUTH0_CLIENT_SECRET}"